" ######## for vundle ##############
set nocompatible              " be iMproved, required
filetype off                  " required

" git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
"
" install plugs
" :PluginInstall
"
" for YCM
" yum install -y automake gcc gcc-c++ kernel-devel cmake python-devel python3-devel
" cd .vim/bundle/YouCompleteMe
" ./install.py


" set the runtime path to include Vundle and initialize
 set rtp+=~/.vim/bundle/Vundle.vim
 call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')
"
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'a.vim'
" syntax for c
Plugin 'c.vim'
" syntax for cpp
Plugin 'cpp.vim'
" ccurately completing C, C++, Objective-C and Objective-C++ code
" used by clang-complete
Plugin 'clang'
Plugin 'hari-rangarajan/CCTree' 
" startup, 
Plugin 'mhinz/vim-startify'
" theme
Plugin 'morhetz/gruvbox'
" If you've got special flags for a project (especially -I and -D ones), clang
" may be unable to complete your code. To overcome this limitation put the
" flags inside the file .clang_complete at the root of your project.  
Plugin 'clang-complete'
Plugin 'ctags.vim'
Plugin 'taglist.vim'
" dir tree
Plugin 'scrooloose/nerdtree'

" go
Plugin 'fatih/vim-go'
" Bundle 'project.tar.gz'
" Plugin 'minibufexpl.vim'
"
"Plugin 'Valloric/YouCompleteMe'

" about code
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'Valloric/MatchTagAlways'
Plugin 'Yggdroot/indentLine'

" " The following are examples of different formats supported.
" " Keep Plugin commands between vundle#begin/end.
" " plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'
" " plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" " Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'
" " git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" " The sparkup vim script is in a subdirectory of this repo called vim.
" " Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" " Install L9 and avoid a Naming conflict if you've already installed a
" " different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}
"
" " All of your Plugins must be added before the following line
 call vundle#end()            " required
 filetype plugin indent on    " required
" " To ignore plugin indent changes, instead use:
" "filetype plugin on
" "
" " Brief help
" " :PluginList       - lists configured plugins
" " :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" " :PluginSearch foo - searches for foo; append `!` to refresh local cache
" " :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
" "
" " see :h vundle for more details or wiki for FAQ
" " Put your non-Plugin stuff after this line

" ########  vundle end ##################################################

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Get out of VI's compatible mode..
set nocompatible
"source $VIMRUNTIME/vimrc_example.vim
"source $VIMRUNTIME/mswin.vim

"Sets how many lines of history VIM har to remember
set history=4000

"Enable filetype plugin
filetype plugin on
filetype indent on

"Set to auto read when a file is changed from the outside
set autoread

"Have the mouse enabled all the time:
" set mouse=v
 
"Set mapleader
let mapleader = ","
let g:mapleader = ","

"Fast saving
nmap <leader>w :wa!<cr>
nmap <leader>q :q!<cr>
nmap <leader>m :wa<cr>:make<cr>:cw<cr><cr>
nmap <leader>k :wa<cr>:! go build<cr>
" nmap <leader>f :find<cr>

""Fast reloading of the .vimrc
"map <leader>s :source ~/vim_local/vimrc<cr>
""Fast editing of .vimrc
"map <leader>e :e! ~/vim_local/vimrc<cr>
""When .vimrc is edited, reload it
"autocmd! bufwritepost vimrc source ~/vim_local/vimrc

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Colors and Fonts
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Enable syntax hl
syntax enable

"if has("gui_running")
"  set guioptions-=T
"else
"  colorscheme evening
"endif

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" VIM userinterface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Set 7 lines to the curors - when moving vertical..
set so=7

"Turn on WiLd menu
set wildmenu

"Always show current position
set ruler

"The commandbar is 2 high
set cmdheight=2

"Show line number
set number
set relativenumber

" cursor
set cursorline
"set cursorcolumn

set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8


"Do not redraw, when running macros.. lazyredraw
set lz

"Change buffer - without saving
set hid

"Set backspace
set backspace=eol,start,indent

"Bbackspace and cursor keys wrap to
set whichwrap+=<,>,h,l

"Ignore case when searching
set ignorecase
set incsearch

"Set magic on
set magic

"No sound on errors.
set noerrorbells
set novisualbell
set t_vb=

"show matching bracets
set showmatch

"How many tenths of a second to blink
set mat=2

"Highlight search things
set hlsearch

""""""""""""""""""""""""""""""
" Statusline
""""""""""""""""""""""""""""""
"Always hide the statusline
set laststatus=2

function! CurDir()
  let curdir = substitute(getcwd(), '/Users/amir/', "~/", "g")
  return curdir
endfunction

"Format the statusline
set statusline=\ %F%m%r%h\ %w\ \ CWD:\ %r%{CurDir()}%h\ \ \ Line:\ %l/%L:%c

" for vim-startify
let g:startify_files_number = 20
let g:startify_change_to_dir = 0

""""""""""""""""""""""""""""""
" Visual
""""""""""""""""""""""""""""""
" From an idea by Michael Naumann
function! VisualSearch(direction) range
  let l:saved_reg = @"
  execute "normal! vgvy"
  let l:pattern = escape(@", '\\/.*$^~[]')
  let l:pattern = substitute(l:pattern, "\n$", "", "")
  if a:direction == 'b'
    execute "normal ?" . l:pattern . "^M"
  else
    execute "normal /" . l:pattern . "^M"
  endif
  let @/ = l:pattern
  let @" = l:saved_reg
endfunction

"Basically you press * or # to search for the current selection !! Really useful
vnoremap <silent> * :call VisualSearch('f')<CR>
vnoremap <silent> # :call VisualSearch('b')<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Moving around and tabs
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Map space to / and c-space to ?
map <space> /
map <c-space> ?

"Smart way to move btw. windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

"Actually, the tab does not switch buffers, but my arrows
"Bclose function ca be found in "Buffer related" section
map <leader>bd :Bclose<cr>
map <down> <leader>bd
"Use the arrows to something usefull
map <right> :bn<cr>
map <left> :bp<cr>

"Tab configuration
map <leader>tn :tabnew %<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove
try
  set switchbuf=usetab
  set stal=2
catch
endtry
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Parenthesis/bracket expanding
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
vnoremap $1 <esc>`>a)<esc>`<i(<esc>
")
vnoremap $2 <esc>`>a]<esc>`<i[<esc>
vnoremap $3 <esc>`>a}<esc>`<i{<esc>
vnoremap $$ <esc>`>a"<esc>`<i"<esc>
vnoremap $q <esc>`>a'<esc>`<i'<esc>
vnoremap $w <esc>`>a"<esc>`<i"<esc>

"Map auto complete of (, ", ', [
inoremap $1 ()<esc>:let leavechar=")"<cr>i
inoremap $2 []<esc>:let leavechar="]"<cr>i
inoremap $4 {<esc>o}<esc>:let leavechar="}"<cr>O
inoremap $3 {}<esc>:let leavechar="}"<cr>i
inoremap $q ''<esc>:let leavechar="'"<cr>i
inoremap $w ""<esc>:let leavechar='"'<cr>i
au BufNewFile,BufRead *.\(vim\)\@! inoremap " ""<esc>:let leavechar='"'<cr>i
au BufNewFile,BufRead *.\(txt\)\@! inoremap ' ''<esc>:let leavechar="'"<cr>i

imap <m-l> <esc>:exec "normal f" . leavechar<cr>a
imap <d-l> <esc>:exec "normal f" . leavechar<cr>a


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General Abbrevs
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"My information
iab xdate <c-r>=strftime("%d/%m/%y %H:%M:%S")<cr>
iab xname Amir Salihefendic


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Editing mappings etc.
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Remap VIM 0
map 0 ^

"Move a line of text using control
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z

set completeopt=menu

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Buffer realted
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Fast open a buffer by search for a name
map <c-q> :sb

""Open a dummy buffer for paste
"map <leader>q :e ~/buffer<cr>

"Restore cursor to file position in previous editing session
set viminfo='10,\"100,:20,%,n~/.viminfo
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

  " Buffer - reverse everything ... :)
  map <F9> ggVGg?

  " Don't close window, when deleting a buffer
  command! Bclose call <SID>BufcloseCloseIt()

  function! <SID>BufcloseCloseIt()
    let l:currentBufNum = bufnr("%")
    let l:alternateBufNum = bufnr("#")

    if buflisted(l:alternateBufNum)
      buffer #
    else
      bnext
    endif

    if bufnr("%") == l:currentBufNum
      new
    endif

    if buflisted(l:currentBufNum)
      execute("bdelete! ".l:currentBufNum)
    endif
  endfunction


  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  " Files and backups
  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  "Turn backup off
  set nobackup
  set nowb
  set noswapfile


  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  " Folding
  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  "Enable folding, I find it very useful
  " Za open/close the expr
  " zo open
  " zc close
  " zM close all
  " zR open all
  set foldmethod=syntax
  set foldlevel=100

  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  " Text options
  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  set expandtab
  set shiftwidth=2

  au FileType c,cpp setlocal cinoptions=:0,g0,(0,w1 shiftwidth=4 tabstop=4

  set smarttab
  set lbr
  set tw=500

  """"""""""""""""""""""""""""""
  " Indent
  """"""""""""""""""""""""""""""
  "Auto indent
  set ai

  "Smart indet
  set si

  "C-style indeting
  set cindent

  "Wrap lines
  set wrap


  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  " YCM
  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  let g:ycm_server_keep_logfiles = 1
  let g:ycm_server_log_level = 'debug'
  let g:ycm_global_ycm_extra_conf= "~/.ycm_extra_conf.py"

  "" go
  let g:go_play_browser_command = ''


  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  " Spell checking
  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  map <leader>sn ]s
  map <leader>sp [s
  map <leader>sa zg
  map <leader>s? z=

  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
  " Plugin configuration
  """""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

  " nerdtree设置
  "autocmd VimEnter * NERDTree
  map <F2> :NERDTreeToggle<CR>
  let NERDTreeIgnore=['\.o$', '\.ko$', '\.so$', '\.a$', '\.swp$', '\.bak$', '\~$']
  let NERDTreeSortOrder=['\/$', 'Makefile', '\.c$', '\.cc$', '\.cpp$', '\.h$', '*', '\~$']
  let NERDTreeMinimalUI=1
  "let NERDTreeWinPos="right"
  let NERDTreeQuitOnOpen=1

  """"""""""""""""""""""""""""""
  " Minibuffer
  """"""""""""""""""""""""""""""
  let g:miniBufExplModSelTarget = 1
  let g:miniBufExplorerMoreThanOne = 2
  let g:miniBufExplModSelTarget = 0
  let g:miniBufExplUseSingleClick = 1
  let g:miniBufExplMapWindowNavVim = 1
  let g:miniBufExplVSplit = 25
  let g:miniBufExplSplitBelow=1

  let g:bufExplorerSortBy = "name"

  autocmd BufRead,BufNew :call UMiniBufExplorer
  """"""""""""""""""""""""""""""
  " Tag list (ctags) - not used
  """"""""""""""""""""""""""""""
  "let Tlist_Ctags_Cmd=$VIMRUNTIME.'/ctags.exe'
  " https://blog.easwy.com/archives/advanced-vim-skills-taglist-plugin/
  let Tlist_Sort_Type = "name"
  let Tlist_Show_Menu = 1
  let Tlist_Auto_Open = 1
  let Tlist_Use_Right_Window=1
  let Tlist_File_Fold_Auto_Close=1
  map <leader>t :Tlist<cr>

  """"""""""""""""""""""""""""""""""""""
  " Filetype generic
  """"""""""""""""""""""""""""""""""""""

  " c/c++ header
  function! s:insert_gates()
    let gatename = substitute(toupper(expand("%:t")), "\\.", "_", "g")
    execute "normal! i#ifndef " . gatename
    execute "normal! o#define " . gatename . " "
    execute "normal! Go#endif /* " . gatename . " */"
    normal! kk
  endfunction

  autocmd BufNewFile *.{h,hpp} call <SID>insert_gates()

  " gruvbox
  se t_Co=256
  colorscheme gruvbox
  set background=dark    " Setting dark mode

