#!/bin/sh

install="yum install -y "
erase="yum erase -y "

$erase vim-minimal
$install vim 
ln -s /usr/bin/vim /bin/vi

# network tools
software="openssh-server wget telnet vsftpd"
# developemnt tools
software+=" gcc gcc-c++ make gdb man man-pages ctags indent cmake"
# monitor tools
software+=" sysstat file tree"
# compress tools
software+=" zip unzip"
# version control tools
software+=" git svn"
# for lscpu,lsblk
software+=" util-linux-ng"

$install $software


/etc/init.d/vsftpd start


function disp
{
	echo "download $1 from $2"
}

# for aspersa
disp "percona" "http://www.percona.com/redir/downloads/percona-toolkit/LATEST/percona-toolkit-2.1.7.tar.gz"

# to display cpu topology
disp "intel performance tuning utility" "http://software.intel.com/en-us/articles/intel-performance-tuning-utility/"
